### ISSUE TITLE
Timestamp issue with nginx error log only

### ISSUE THREAD

**Issue by nshah14285** [graylog-labs/graylog-contentpack-nginx#10]
Any idea, why timestamp is showing different in nginx_error log.
Timezone set on graylog server and source server is 'Europe/Berlin'.
As per attached screenshot, Graylog shows 1 hour late logs of nginx_error inside stream messages.

Rest of the nginx logs time are coming properly except nginx error log time.

Please find attached file.
![screenshot](https://user-images.githubusercontent.com/34057870/33477108-6b3555ea-d6aa-11e7-8fe1-7a0c2d51912b.png)

Thanks,
Nishit Shah

**Comment by joschi** [comment]
@nshah14285 I think everything is fine. The timestamp in the nginx log message is supposed to be UTC.

Graylog (or rather this content pack) extracted the correct timestamp (2017-12-01T08:01:04.000Z) and displays it in your custom timezone (Europe/Berlin is currently GMT+1).

If you think that's incorrect, you could write a pipeline rule to set the "timestamp" field to another timezone.

**Comment by nshah14285** [comment]
Timestamp stored in nginx_error_log file is 'Europe/Berlin' and not 'UTC' on source server.

There are logs captured in nginx_error log file on source server after 2017/12/01 09:01:04 but in graylog it gets delayed by 1 hour due to some timestamp issue. So the error message of 2017/12/01 10:01:04 will be displayed when graylog timestamp is 2017-12-01 11:01:04.

So don't know where exactly the issue is.

Any idea?

**Comment by joschi** [comment]
As I wrote before, when the timezone information is missing, Graylog expects the timestamps to be in UTC.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by nshah14285** [comment]
OK, next time onwards, I will post the issue in discussion forum.
I was not aware about that.

Thank You.
