### ISSUE TITLE
Link in description in content_pack.json is broken

### ISSUE THREAD

**Issue by Nothing4You** [graylog-labs/graylog-contentpack-nginx#8]
content_pack.json links to http://www.graylog2.org/content-packs/547b5021e4b0a06d87eea01e which doesn't exist anymore. I guess it should be https://marketplace.graylog.org/addons/572ff823-62cc-468e-af17-300bcfd9932d now.

**Comment by joschi** [comment]
@Nothing4You Good catch, thanks!
