### ISSUE TITLE
Routing to streams are not working

### ISSUE THREAD

**Issue by tumichnix** [graylog-labs/graylog-contentpack-nginx#9]
Hi,

graylog receives a lot of messages over the two inputs.
But the routing into the different streams (eg. "nginx request") dosent work. Alle messages are routed into the "All messages" stream.

If I test against a stream everything is fine.

Any ideas?

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
